/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitorjclima.controledeintervencoes.view;

import br.com.vitorjclima.controledeintervencoes.core.controller.EquipamentoJpaController;
import br.com.vitorjclima.controledeintervencoes.core.controller.SistemaMedicaoJpaController;
import br.com.vitorjclima.controledeintervencoes.core.controller.ToleranciaJpaController;
import br.com.vitorjclima.controledeintervencoes.db.Equipamento;
import br.com.vitorjclima.controledeintervencoes.db.SistemaMedicao;
import br.com.vitorjclima.controledeintervencoes.db.Tolerancia;
import java.awt.Cursor;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class CadastroToleranciaView extends javax.swing.JFrame {

    private EquipamentoJpaController equipamentoController;
    private Equipamento equipamento;
    private SistemaMedicaoJpaController sistemaMedicaoController;
    private SistemaMedicao sistemaMedicao;
    private Tolerancia tolerancia;
    private ToleranciaJpaController toleranciaController;
    private Principal principal;

    /**
     * Creates new form CadastroToleranciaView
     */
    public CadastroToleranciaView() {
        initComponents();
        equipamentoController = new EquipamentoJpaController();
        sistemaMedicaoController = new SistemaMedicaoJpaController();
        toleranciaController = new ToleranciaJpaController();
        carregaEquipamentos();
        carregaSistemaMedicao();

    }

    public CadastroToleranciaView(Principal principal) {
        initComponents();
        equipamentoController = new EquipamentoJpaController();
        sistemaMedicaoController = new SistemaMedicaoJpaController();
        toleranciaController = new ToleranciaJpaController();
        this.principal = principal;
        carregaEquipamentos();
        carregaSistemaMedicao();

    }

    private void cursorWait() {
        Cursor ponteiroMouse = new Cursor(Cursor.WAIT_CURSOR);
        setCursor(ponteiroMouse);
    }

    private void cursorDefault() {
        Cursor ponteiroMouse = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(ponteiroMouse);
    }

    private void carregaEquipamentos() {
        cursorWait();
        equipamentoComboBox.removeAllItems();

        List<Equipamento> lista = equipamentoController.findEquipamentoEntities();

        for (Iterator itr = lista.iterator(); itr.hasNext();) {
            Equipamento equip = (Equipamento) itr.next();

            equipamentoComboBox.addItem(equip.getEquipamentoId() + " - " + equip.getEquipamentoDescricao());
        }
        cursorDefault();
    }

    private void carregaSistemaMedicao() {
        cursorWait();
        sistemaMedicaoComboBox.removeAllItems();

        List<SistemaMedicao> lista = sistemaMedicaoController.findSistemaMedicaoEntities();

        for (Iterator itr = lista.iterator(); itr.hasNext();) {
            SistemaMedicao sistM = (SistemaMedicao) itr.next();

            sistemaMedicaoComboBox.addItem(sistM.getSistemaMedicaoId());
        }
        cursorDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEquipamento = new javax.swing.JLabel();
        equipamentoComboBox = new javax.swing.JComboBox();
        labelCondicao = new javax.swing.JLabel();
        sistemaMedicaoComboBox = new javax.swing.JComboBox();
        labelTolerancia = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        toleranciaEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tolerância");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        labelEquipamento.setText("Equipamento");

        equipamentoComboBox.setToolTipText("Selecione a condição atual do equipamento");
        equipamentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipamentoComboBoxActionPerformed(evt);
            }
        });

        labelCondicao.setText("Sistema de Medição");

        sistemaMedicaoComboBox.setToolTipText("Selecione a condição atual do equipamento");
        sistemaMedicaoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemaMedicaoComboBoxActionPerformed(evt);
            }
        });

        labelTolerancia.setText("Tolerância");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEquipamento)
                            .addComponent(labelCondicao)
                            .addComponent(labelTolerancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sistemaMedicaoComboBox, 0, 181, Short.MAX_VALUE)
                            .addComponent(equipamentoComboBox, 0, 181, Short.MAX_VALUE)
                            .addComponent(toleranciaEntrada)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(botaoSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEquipamento)
                    .addComponent(equipamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCondicao)
                    .addComponent(sistemaMedicaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toleranciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTolerancia))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void equipamentoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipamentoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipamentoComboBoxActionPerformed

    private void sistemaMedicaoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemaMedicaoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sistemaMedicaoComboBoxActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        tolerancia = new Tolerancia();

        String[] equipId = equipamentoComboBox.getModel().getSelectedItem().toString().split(" - ");
        tolerancia.setEquipamentoId(Integer.parseInt(equipId[0]));

        tolerancia.setSistemaMedicaoId(sistemaMedicaoComboBox.getModel().getSelectedItem().toString());
        
        String a = toleranciaEntrada.getText().replace(',', '.');
        System.out.println("Numero: "+a);
        
        
        tolerancia.setToleranciaValor(Double.parseDouble(a));

        cursorWait();

        if (toleranciaEntrada.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve preencher a tolerância");
        } else {
            try {
                this.toleranciaController.create(tolerancia);
                JOptionPane.showMessageDialog(this, "Cadastro efetuado com sucesso");
                this.dispose();
                this.principal.setEnabled(true);
            } catch (Exception ex) {
                Logger.getLogger(Tolerancia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        cursorDefault();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        this.principal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroToleranciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroToleranciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroToleranciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroToleranciaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroToleranciaView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox equipamentoComboBox;
    private javax.swing.JLabel labelCondicao;
    private javax.swing.JLabel labelEquipamento;
    private javax.swing.JLabel labelTolerancia;
    private javax.swing.JComboBox sistemaMedicaoComboBox;
    private javax.swing.JTextField toleranciaEntrada;
    // End of variables declaration//GEN-END:variables
}
